---

run:
  deadline: 5m

output:
  sort-results: true

linters-settings:
  errcheck:
    exclude: errcheck_excludes.txt
  goimports:
    local-prefixes: github.com/grpc-ecosystem/go-grpc-middleware/v2
  gofumpt:
    extra-rules: true